<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
<script>
    /*
    目标：进一步理解JS中的错误和错误处理

    1.错误的类型
        Error：所有错误的父类型
        ReferenceError：引用的变量不存在
        TypeError：数据类型不正确的错误
        RangeError：数据值不在其所允许的范围内
        SyntaxError：语法错误
    2.错误处理
        捕获错误：try ... catch
        抛出错误：throw error
    3.错误对象
        message属性：错误相关信息
        stack属性：函数调用栈记录信息        
    */
    //1.常见的内置错误
    //1).ReferenceError:引用的变量不存在
    // console.log(a);  a is not defined
    
    //TypeError:数据类型不正确的错误
    //let b = null
    //console.log(b.xxx);  Cannot read property 'xxx' of null

    //RangeError
    // function fn(){
    //     fn()
    // }
    // fn() //Maximum call stack size exceeded

    //SyntaxError
    //const c = """" Unexpected string

    //2.错误处理
    //捕获错误
    try {
        let d
        console.log(d.xxx);
    } catch (error) {
        console.log(error.message);
        console.log(error.stack);
    }
    console.log("出错之后");
    //抛出错误
    function something(){
        if(Date.now() % 2 === 1){
            console.log("当前时间为奇数，可以执行任务");
        } else{ //抛出异常由调用者自己处理
            throw new Error('当前时间为偶数，不可以执行任务')
        }
    }
    try {
        something()
    } catch (error) {
        console.log(error.message);
    }
</script>
</html>